diagnose_function <- function(network, cases) {
  # Do not forgett the burnout period!! Ie. Discard the 100 or so first samples generated by my MCMC Metropolis in Gibbs algorithm. 
  
  random_values <- runif(10000) # can be made more or less depending on how many I need, just took an abitrary number. 
  output_matrix <- matrix(rep(1,40), ncol = 4)
  # The MCMC Metropolis in Gibbs algorithm: 
  working_array <- numeric(9)
  
  assign_0_or_1 <- function(random_values, random_number_index) {
    if (sample(random_values,1) > 0.5) {
      return(1)
    }
    else {
      return(0)
    }
  }
  
  for (i in 1:10) {
    
    # Load the working array:
    for (j in 1:9) {
      working_array[j] <- cases[i,j]
    }
    
    # assign the unknown variables with a random value: 
    working_array[1] <- assign_0_or_1(random_values)
    working_array[4] <- assign_0_or_1(random_values)
    working_array[6] <- assign_0_or_1(random_values)
    working_array[7] <- assign_0_or_1(random_values)
    proposed_value <- 0
    if (working_array[1] == 0) {
      proposed_value <- 1
    }
    # Calculating the contitional attributes: 
    p_old <- network$Pn[1,working_array[1]]*dnorm(working_array[2], network$temperature[[network]]
    
  }
  
  
  
  
}